services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Basilicom\DataQualityBundle\Controller\:
      resource: '../../Controller'
      public: true
      tags: ['controller.service_arguments']

    Basilicom\DataQualityBundle\Command\:
      resource: '../../Command'
      public: true
      tags: ['command.service_arguments']

    Basilicom\DataQualityBundle\Tools\Installer:
      public: true
      arguments:
        $bundle: "@=service('kernel').getBundle('DataQualityBundle')"

    Basilicom\DataQualityBundle\Registry\RuleRegistry:
      public: true

    Basilicom\DataQualityBundle\Definition\NotEmptyDefinition:
      public: true
      tags:
        - { name: data_quality.rule, key: 'Not Empty' }

    Basilicom\DataQualityBundle\Definition\MinimumStringLengthDefinition:
      public: true
      tags:
        - { name: data_quality.rule, key: 'Minimum String Length' }

    Basilicom\DataQualityBundle\DefinitionsCollection\Factory\FieldDefinitionFactory:
      public: true

    Symfony\Component\ExpressionLanguage\ExpressionLanguage:
      public: false

    Basilicom\DataQualityBundle\Definition\GateFactory:
      public: true

    Basilicom\DataQualityBundle\Resolver\FieldPathResolverInterface: '@Basilicom\DataQualityBundle\Resolver\FieldPathResolver'

    Basilicom\DataQualityBundle\Resolver\FieldPathResolver:
      public: true

    Basilicom\DataQualityBundle\Service\DataQualityService:
      public: true

    Basilicom\DataQualityBundle\Provider\DataQualityProvider:
      public: true

    Basilicom\DataQualityBundle\Model\Listener\ObjectPreSaveListener:
      tags:
        - { name: kernel.event_listener, event: pimcore.dataobject.preAdd, method: onPreSave }
        - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreSave }

    Basilicom\DataQualityBundle\EventSubscriber\:
      resource: '../../EventSubscriber/'

    Basilicom\DataQualityBundle\EventSubscriber\DataQualityConfigPreSaveSubscriber:
      tags:
        - { name: kernel.event_listener, event: pimcore.dataobject.preAdd, method: onPreSave }
        - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreSave }

    Basilicom\DataQualityBundle\Command\UpdateDataQualityCommand:
      tags:
        - { name: console.command, command: 'dataquality:update' }

    Basilicom\DataQualityBundle\Command\UpdateAllDataQualityCommand:
      tags:
        - { name: console.command, command: 'dataquality:update-all' }

    #
    # custom Renderer
    #
    custom_renderer.data_quality_config:
      class: Basilicom\DataQualityBundle\Model\Renderer\DataQualityConfigRenderer
      public: true

    #
    # option providers
    #
    options_provider.object_classes:
      class: Basilicom\DataQualityBundle\Model\Provider\ObjectClassesProvider
      public: true

    options_provider.object_fields:
      class: Basilicom\DataQualityBundle\Model\Provider\ObjectFieldsProvider
      public: true

    options_provider.definitions:
      class: Basilicom\DataQualityBundle\Model\Provider\DefinitionsProvider
      public: true

    options_provider.data_quality_languages:
      class: Basilicom\DataQualityBundle\Model\Provider\DataQualityLanguagesProvider
      public: true
