<?php

declare(strict_types=1);

namespace Pimcore\Model\DataObject\Fieldcollection\Data;

/**
 * Stand-in for the Pimcore-generated `DataQualityFieldDefinition`
 * field-collection class. The real class lives in `var/classes/` and
 * is regenerated by the bundle installer; kernel-free tests need the
 * type to exist so `FieldDefinitionFactory::get(...)` can type-check
 * against the field-collection item and so DependencyResolver can
 * walk a real `Fieldcollection`'s items.
 */
class DataQualityFieldDefinition extends AbstractData
{
    private ?string $field = null;

    private ?string $condition = null;

    private ?string $parameters = null;

    private ?float $weight = null;

    private ?string $gate = null;

    private ?string $group = null;

    public function getField(): ?string
    {
        return $this->field;
    }

    public function setField(?string $value): self
    {
        $this->field = $value;

        return $this;
    }

    public function getCondition(): ?string
    {
        return $this->condition;
    }

    public function setCondition(?string $value): self
    {
        $this->condition = $value;

        return $this;
    }

    public function getParameters(): ?string
    {
        return $this->parameters;
    }

    public function setParameters(?string $value): self
    {
        $this->parameters = $value;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $value): self
    {
        $this->weight = $value;

        return $this;
    }

    public function getGate(): ?string
    {
        return $this->gate;
    }

    public function setGate(?string $value): self
    {
        $this->gate = $value;

        return $this;
    }

    public function getGroup(): ?string
    {
        return $this->group;
    }

    public function setGroup(?string $value): self
    {
        $this->group = $value;

        return $this;
    }
}
