<?php

declare(strict_types=1);

namespace Pimcore\Model\DataObject;

/**
 * Generated by Pimcore's bundle installer in production
 * (`var/classes/DataObject/DataQualityConfig.php`). Kernel-free tests
 * need it to satisfy the `DataQualityConfig` typehints in `RuleContext`
 * and `DataQualityProvider`, so a minimal subclass of `Concrete` stands
 * in. The real generated class adds Pimcore-managed getters/setters
 * not exercised by unit tests.
 */
class DataQualityConfig extends Concrete
{
    /** @var string[]|null */
    private ?array $dataQualityLanguages = null;

    private ?string $dataQualityName = null;

    /**
     * @return string[]|null
     */
    public function getDataQualityLanguages(): ?array
    {
        return $this->dataQualityLanguages;
    }

    /**
     * @param string[]|null $value
     */
    public function setDataQualityLanguages(?array $value): void
    {
        $this->dataQualityLanguages = $value;
    }

    public function getDataQualityName(): ?string
    {
        return $this->dataQualityName;
    }

    public function setDataQualityName(?string $value): void
    {
        $this->dataQualityName = $value;
    }
}
