<?php

declare(strict_types=1);

namespace Pimcore\Model\DataObject;

/**
 * Generated by Pimcore's bundle installer in production
 * (`var/classes/DataObject/DataQualityConfig.php`). Kernel-free tests
 * need it to satisfy the `DataQualityConfig` typehints in `RuleContext`
 * and `DataQualityProvider`, so a minimal subclass of `Concrete` stands
 * in. The real generated class adds Pimcore-managed getters/setters
 * not exercised by unit tests.
 */
class DataQualityConfig extends Concrete
{
}
